site_name: LightGraphs.jl
site_author: Seth Bromberger
repo_url: https://github.com/JuliaGraphs/LightGraphs.jl/
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['about.md', 'About']
- ['gettingstarted.md', 'Getting Started']
- ['basicmeasures.md', 'Basic Functions & Measurements']
- ['operators.md', 'Operators']
- ['pathing.md', 'Pathing and Traversal']
- ['distance.md', 'Distance Measures']
- ['centrality.md', 'Centrality Measures']
- ['linalg.md', 'Linear Algebra']
- ['generators.md', 'Graph Generators']
- ['persistence.md', 'Reading / Writing Graphs']
- ['integration.md', 'Integration with other Packages']

docs_dir: 'doc'
markdown_extensions: ['extra', 'mathjax']
extra_css: ['LightGraphs.css']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
